package main

//go:generate sh -c "(printf '// Code generated by gojsonstruct and gomodifytags; DO NOT EDIT.\n\n'; go run github.com/twpayne/go-jsonstruct/v3/cmd/gojsonstruct@latest --type-name Config --omitempty-tags always config.json) > config_generated.go"
//go:generate go run github.com/fatih/gomodifytags@latest -file config_generated.go -struct Config -add-tags required:true -quiet -w
