package main

import (
	"context"
	"flag"
	"fmt"
	"net"
	"net/url"
	"os"
	"path/filepath"
	"strings"

	"github.com/altshiftab/gcp_utils/pkg/http/client_code_generation"
	"github.com/altshiftab/x/endpoints"
	"github.com/vphpersson/type_generation/pkg/producers/postgres"
	"golang.org/x/sync/errgroup"
)

var extensions = []string{"pgcrypto", "citext"}

func main() {
	// Flags for output destinations
	typescriptOutPath := flag.String("typescript-output", "", "Write TypeScript output to this file (default: stdout)")
	postgresOutPath := flag.String("postgres-output", "", "Write Postgres output to this file (default: stdout)")
	flag.Parse()

	errGroup, _ := errgroup.WithContext(context.Background())

	var typescriptOutput string
	var postgresOutput string

	errGroup.Go(
		func() error {
			baseUrl := &url.URL{
				Scheme: "http",
				Host:   net.JoinHostPort(endpoints.Domain, endpoints.Port),
			}

			out, err := client_code_generation.Render(
				endpoints.EndpointSpecificationGetters,
				baseUrl,
			)
			if err != nil {
				return fmt.Errorf("client code generation render: %w", err)
			}

			typescriptOutput = fmt.Sprintf("// Code generated by type_generation; DO NOT EDIT.\n\n%s\n", out)

			return nil
		},
	)

	errGroup.Go(
		func() error {
			out, err := postgres.Convert(struct{}{})
			if err != nil {
				return fmt.Errorf("postgres convert: %w", err)
			}

			var extensionStrings []string
			for _, extension := range extensions {
				extensionStrings = append(extensionStrings, fmt.Sprintf("CREATE EXTENSION IF NOT EXISTS %s;", extension))
			}

			postgresOutput = fmt.Sprintf(
				"-- Code generated by type_generation; DO NOT EDIT.\n\n%s\n\n%s\n",
				strings.Join(extensionStrings, "\n"),
				out,
			)

			return nil
		},
	)

	if err := errGroup.Wait(); err != nil {
		panic(err)
	}

	if *typescriptOutPath != "" {
		if err := os.MkdirAll(filepath.Dir(*typescriptOutPath), 0o755); err != nil {
			panic(fmt.Errorf("creating typescript output dir: %w", err))
		}
		if err := os.WriteFile(*typescriptOutPath, []byte(typescriptOutput), 0o600); err != nil {
			panic(fmt.Errorf("writing typescript output: %w", err))
		}
	} else {
		fmt.Println(typescriptOutput)
	}

	if *postgresOutPath != "" {
		if err := os.MkdirAll(filepath.Dir(*postgresOutPath), 0o755); err != nil {
			panic(fmt.Errorf("creating postgres output dir: %w", err))
		}
		if err := os.WriteFile(*postgresOutPath, []byte(postgresOutput), 0o600); err != nil {
			panic(fmt.Errorf("writing postgres output: %w", err))
		}
	} else {
		fmt.Println(postgresOutput)
	}
}
