package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/vphpersson/type_generation/pkg/producers/postgres"
)

var extensions = []string{"pgcrypto", "citext"}

func main() {
	var outPath string
	flag.StringVar(&outPath, "out", "", "Write SQL output to this file (default: stdout)")
	flag.Parse()

	// TODO: Add input.
	out, err := postgres.Convert()
	if err != nil {
		panic(fmt.Errorf("postgres convert: %w", err))
	}

	var extensionStrings []string
	for _, extension := range extensions {
		extensionStrings = append(extensionStrings, fmt.Sprintf("CREATE EXTENSION IF NOT EXISTS %s;", extension))
	}

	postgresOutput := fmt.Sprintf(
		"-- Code generated by sql_generation; DO NOT EDIT.\n\n%s\n\n%s\n",
		strings.Join(extensionStrings, "\n"),
		out,
	)

	if outPath != "" {
		if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
			panic(fmt.Errorf("creating postgres output dir: %w", err))
		}
		if err := os.WriteFile(outPath, []byte(postgresOutput), 0o600); err != nil {
			panic(fmt.Errorf("writing postgres output: %w", err))
		}
	} else {
		fmt.Println(postgresOutput)
	}
}
